#!/usr/bin/env python
from __future__ import print_function

from nadex import NadexRestApi

client = NadexRestApi()
client.Account.login()

from nadex.resources import Order

order = Order(price=1.13366, direction='+', epic='EURUSD', size=1)

print(client.Order.create(order))
