#!/usr/bin/env python
from __future__ import print_function

from nadex import NadexRestApi

client = NadexRestApi()
client.Account.login()

# get list of markets
markets = client.Market.all()
for m in markets:
    print(m.id, m.name)

    # get details of the market. e.g. Commodity market has Oil, Corn, etc.
    detail = client.Market.get(m.id)
    for d in detail:
        print("  ", d.id, d.name)
