#!/usr/bin/env python
from __future__ import print_function

from nadex import NadexRestApi

client = NadexRestApi()
client.Account.login()

target_market = 'Forex Binaries'
target_instrument = 'EUR/USD'

markets = client.Market.all()
for m in markets:
    if m.name == target_market:
        print(m.id, m.name)
        # get list of instruments for the market
        instruments = client.Market.get(m.id)
        for instrument in instruments:
            if instrument.name == target_instrument:
                print(instrument.id, instrument.name)
                serieses = client.Timeseries.get(instrument.id)
                epic = None
                for series in serieses:
                    # print(series.id, series.name)
                    contracts = client.Contract.get(series.id)
                    for contract in contracts:
                        print(series.id, series.name, contract.epic, contract.bestBid or ' -- ', contract.bestOffer or ' -- ')
                break
        break
