#!/usr/bin/env python
from __future__ import print_function

from nadex import NadexRestApi

client = NadexRestApi()
client.Account.login()

# get list of markets
target_market = 'Forex Binaries'
target_instrument = 'GBP/USD'

markets = client.Market.all()
for m in markets:
    if m.name == target_market:
        print(m.name)
        # get list of instruments for the market
        instruments = client.Market.get(m['id'])
        for i in instruments:
            if i.name == target_instrument:
                print(i.name)
                instrument_id = i.name
                series = client.Timeseries.get(i.id)
                for s in series:
                    print(s.id, s.name)
                break
        break
